### ISSUE TITLE
Unable to upload attachments files, other than JPGs, using Bulk-Submission

### ISSUE THREAD

**Issue by mdestaubin** [kobotoolbox/kobocat#587] opened 2019-11-05 15:23 UTC
## Description

Unable to upload PNG images and other attachments file types using `bulk-submission`. 

## Steps to Reproduce

1. Manually export submissions that have PNG and other file attachments (eg Word doc, PDFs) using the  [bulk-submission](http://support.kobotoolbox.org/en/articles/592375-manually-uploading-submissions) method.

2. Upload the zip file at either:
https://kc.humanitarianresponse.info/your_username/bulk-submission-form 
https://kc.kobotoolbox.org/your_username/bulk-submission-form 

[Zip File Example](https://github.com/kobotoolbox/kobocat/files/3815259/apsdTauwnf7rPQ8yAZeoLp_2019_11_05_13_45_46.zip)

## Expected behavior 

You should see the PNG image files in the media gallery on your project page and be able to download all the file attachments with the Media Attachment export option. 

## Actual behavior 

The submissions appear successful, but the attachments do not appear in either the media gallery or in the media attachment exports.

## Additional details

JPGs work as expected.

[Community Forum Topic](https://community.kobotoolbox.org/t/missing-media-after-manual-bulk-submission/6028/5)

**Comment by jnm** [comment] 2019-11-07 21:40
Duplicate of #434

**Comment by tinok** [comment] 2020-10-08 14:48
Closing because duplicate of #434.

**Closed by tinok** 2020-10-08 14:48 UTC
Labels: bug
