### ISSUE TITLE
ODK Briefcase

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/kobocat#339] opened 2017-03-17 04:24 UTC
Hi,
I'm using kobo-docker and since one month or more users are unable to pull data from the server using ODK briefcase, I thought it might be version conflict but after trying all below versions of briefcase it is sure that issue relies on server.

1. Version 1.4.10 - April 22, 2016
2. Version 1.4.9 - April 22, 2016
3. Version 1.4.6 - August 24, 2015
4. Version 1.4.5 - January 9, 2015
5. Version 1.4.4 - August 24, 2014

Same errors are populated from [https://kc.humanitarianresponse.info](url) and [https://kc.kobotoolbox.org](url).

Error Message 
> Fetching form definition
resolving against briefcase form definitions
Error parsing form definition: org.opendatakit.aggregate.exception.ODKIncompleteSubmissionData: The data model does not have an id or xmlns attribute.  Add an id="your.domain.org:formId" attribute to the top-level instance data element of your form

**Comment by HenrikEsbensen** [comment] 2017-08-05 23:58
I'm having this problem as well, using the latest version of Briefcase, 1.7.0. What is the status? What is the ETA on a fix? Thanks a lot!
- Henrik

**Comment by aurdipas** [comment] 2018-03-21 11:14
no fix to this?

**Comment by tinok** [comment] 2018-03-22 17:50
I just checked this again with 1.9 as it was working fine for me. The issue is that forms deployed through KPI are not usable in Briefcase, whereas forms deployed through legacy/kobocat are still working. Here is a comparison of two similar forms, the first of which works (Pull in Briefcase succeeds) and the second doesn't (Briefcase shows error shown above). 

[briefcase.zip](https://github.com/kobotoolbox/kobocat/files/1838664/briefcase.zip)

I'm not seeing a reason why one fails and the other succeeds, though. @jnm

**Comment by tinok** [comment] 2018-03-22 17:57
Another form that also succeeded was deployed through KPI, so my above theory falls apart. 

[alsoworks.xml.zip](https://github.com/kobotoolbox/kobocat/files/1838675/alsoworks.xml.zip)

**Comment by tinok** [comment] 2018-03-23 17:16
I just tried reproducing the successful pull by redeploying the same form as a new project but the new project now has the same issue in Briefcase. 

The error is thrown by Briefcase because of [this section](https://github.com/opendatakit/briefcase/blob/57eea1d7782da7ad77794530d503f182e02f6ad8/src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java#L560-L563), implying that there is an ID missing. But the ID is where it should be, and the form is created through pyxform anyway. 

Below is the XML converted that doesn't work with Briefcase, even though it was a redeployed version of the last one that worked (see above, alsoworks.xml). 

[shouldwork.xml.zip](https://github.com/kobotoolbox/kobocat/files/1842723/shouldwork.xml.zip)

**Comment by MartijnR** [comment] 2018-03-23 17:37
Looks like it's the version number (despite the error message). I think Aggregate (and Briefcase) require a specific timestamp format.

See minimal forms below:

[Archive.zip](https://github.com/kobotoolbox/kobocat/files/1842820/Archive.zip)

**Comment by MartijnR** [comment] 2018-03-23 17:40
version checking code: https://github.com/opendatakit/briefcase/blob/57eea1d7782da7ad77794530d503f182e02f6ad8/src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java#L752-L778

**Comment by tinok** [comment] 2018-03-23 17:42
Created issue https://github.com/opendatakit/briefcase/issues/423

@MartijnR could it be that the reason is the non-integer version string in kpi's forms?

**Comment by tinok** [comment] 2018-04-04 00:36
Closing this issue as a fix has been written in the Briefcase code. A new version will be released shortly by their awesome team.

**Closed by tinok** 2018-04-04 00:36 UTC
