### ISSUE TITLE
ConnectionDoesNotExist at /me/

### ISSUE THREAD

**Issue by sarveshwaranj** [kobotoolbox/kobocat#564] opened 2019-08-05 05:43 UTC
I have got this problem after running all the kpi, kobocat and enketo

Request Method: | GET
-- | --
http://192.168.1.24:8003/me/
1.8.19
ConnectionDoesNotExist
The connection kobocat doesn't exist
/home/ewall-py-02/environment/kobotoolbox/local/lib/python2.7/site-packages/django/db/utils.py in ensure_defaults, line 171
/home/ewall-py-02/environment/kobotoolbox/bin/python
2.7.15
['/home/ewall-py-02/Desktop/kobotoolbox_dev/kpi',  '/home/ewall-py-02/environment/kobotoolbox/lib/python2.7',  '/home/ewall-py-02/environment/kobotoolbox/lib/python2.7/plat-x86_64-linux-gnu',  '/home/ewall-py-02/environment/kobotoolbox/lib/python2.7/lib-tk',  '/home/ewall-py-02/environment/kobotoolbox/lib/python2.7/lib-old',  '/home/ewall-py-02/environment/kobotoolbox/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/home/ewall-py-02/environment/kobotoolbox/local/lib/python2.7/site-packages',  '/home/ewall-py-02/environment/kobotoolbox/src/django-digest',  '/home/ewall-py-02/environment/kobotoolbox/src/formpack/src',  '/home/ewall-py-02/environment/kobotoolbox/lib/python2.7/site-packages',  '/home/ewall-py-02/Desktop/kobotoolbox_dev/kpi']
Mon, 5 Aug 2019 05:32:39 +0000
 How to solve this problem

**Comment by jnm** [comment] 2019-08-06 02:07
Duplicate of https://github.com/kobotoolbox/kpi/issues/2339. Please post your question in https://community.kobotoolbox.org/c/kobo-install.

**Closed by jnm** 2019-08-06 02:07 UTC
