### ISSUE TITLE
ODK Briefcase Bug

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/kobocat#359] opened 2017-04-28 04:10 UTC
Dear Team,

I wanted to download my data using kobo briefcase but it gives me following error. please advise. 

> 
Fetching form definition
resolving against briefcase form definitions
Error parsing form definition: org.opendatakit.aggregate.exception.ODKIncompleteSubmissionData: The data model does not have an id or xmlns attribute.  Add an id="your.domain.org:formId" attribute to the top-level instance data element of your form.

**Comment by aurdipas** [comment] 2018-03-21 11:13
any update?

**Comment by smutnyleszek** [comment] 2018-03-21 11:16
Isn't this a duplicate of #359?

**Comment by aurdipas** [comment] 2018-03-21 11:19
Do you mean of #339? it looks nobody is working on these issues. No more compatibility between Kobo and Briefcase?

**Comment by smutnyleszek** [comment] 2018-03-21 13:47
Yes, thanks :) I just think both issues are about the same, so they should be merged and discussion should take place in one of them.

**Comment by tinok** [comment] 2018-03-22 18:00
Duplicate of #359, closing this issue.

**Closed by tinok** 2018-03-22 18:00 UTC
